# Generated by Django 5.2.8 on 2025-11-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('genero', models.CharField(choices=[('ACC', 'Acción'), ('COM', 'Comedia'), ('DRA', 'Drama'), ('SCI', 'Ciencia Ficción'), ('TER', 'Terror'), ('ROM', 'Romance')], max_length=3)),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('sinopsis', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
